## Where the samples will be written
save_data: data
## Where the vocab(s) will be written
src_vocab: vocab/example.vocab.src
tgt_vocab: vocab/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: True

# Corpus opts:
data:
    corpus_1:
        path_src: src-train.txt
        path_tgt: tgt-train.txt
    valid:
        path_src: src-val.txt
        path_tgt: tgt-val.txt
